Repository rafalp/Misago, pull requests merged in 2018-12, with the labels that each got.

#1143 Remove global state from users bans
  misago/threads/api/postendpoints/edits.py
  misago/threads/api/threadposts.py
  misago/threads/viewmodels/posts.py
  misago/users/api/auth.py
  misago/users/api/users.py
  misago/users/apps.py
  misago/users/bans.py
  misago/users/constants.py
  misago/users/forms/auth.py
  misago/users/management/commands/invalidatebans.py
  misago/users/middleware.py
  misago/users/migrations/0003_bans_version_tracker.py
  misago/users/migrations/0017_move_bans_to_cache_version.py
  misago/users/models/ban.py
  misago/users/online/utils.py
  misago/users/social/pipeline.py
  misago/users/tests/test_bans.py
  misago/users/tests/test_invalidatebans.py
  misago/users/tests/test_online_utils.py
  misago/users/tests/test_social_pipeline.py
  misago/users/viewmodels/activeposters.py
  misago/users/viewmodels/followers.py
  misago/users/viewmodels/rankusers.py
  misago/users/views/activation.py
  misago/users/views/forgottenpassword.py
  misago/users/views/profile.py
Labels: backend, enhancement

#1149 Remove misago.core.threadstore
  devproject/settings.py
  misago/acl/migrations/0002_acl_version_tracker.py
  misago/admin/views/generic/list.py
  misago/categories/tests/test_category_model.py
  misago/categories/tests/test_utils.py
  misago/conf/dynamicsettings.py
  misago/conf/tests/test_context_processors.py
  misago/conf/tests/test_migrationutils.py
  misago/core/cachebuster.py
  misago/core/middleware.py
  misago/core/migrationutils.py
  misago/core/tests/test_cachebuster.py
  misago/core/tests/test_migrationutils.py
  misago/core/tests/test_threadstore.py
  misago/core/testutils.py
  misago/core/threadstore.py
  misago/threads/tests/test_threadslists.py
  misago/threads/tests/test_utils.py
  misago/users/forms/admin.py
  misago/users/tests/test_activepostersranking.py
  misago/users/tests/test_users_api.py
  misago/users/testutils.py
  misago/users/views/admin/users.py
Labels: backend, enhancement

#1152 Move recently written tests to pytest
  misago/acl/test.py
  misago/acl/tests/test_acl_algebra.py
  misago/acl/tests/test_getting_user_acl.py
  misago/acl/tests/test_mock_role_admin_form_data.py
  misago/acl/tests/test_patching_user_acl.py
  misago/acl/tests/test_providers.py
  misago/acl/tests/test_roleadmin_views.py
  misago/acl/tests/test_serializing_user_acl.py
  misago/acl/tests/test_testutils.py
  misago/acl/tests/test_user_acl_context_processor.py
  misago/acl/tests/test_user_acl_middleware.py
  misago/acl/testutils.py
  misago/cache/tests/conftest.py
  misago/cache/tests/test_assert_invalidates_cache.py
  misago/cache/tests/test_cache_versions_middleware.py
  misago/cache/tests/test_getting_cache_versions.py
  misago/cache/tests/test_invalidate_caches_management_command.py
  misago/cache/tests/test_invalidating_caches.py
  misago/categories/tests/test_permissions_admin_views.py
  misago/conf/dynamicsettings.py
  misago/conf/tests/conftest.py
  misago/conf/tests/test_context_processors.py
  misago/conf/tests/test_dynamic_settings_middleware.py
  misago/conf/tests/test_getting_dynamic_settings_values.py
  misago/conf/tests/test_getting_static_settings_values.py
  misago/conf/tests/test_overridding_dynamic_settings.py
  misago/conftest.py
  requirements.in
  requirements.txt
Labels: backend, enhancement

#1156 Check templates formatting
  misago/templates/misago/acl_debug.html
  misago/templates/misago/activation/request.html
  misago/templates/misago/activation/stopped.html
  misago/templates/misago/admin/agreements/form.html
  misago/templates/misago/admin/agreements/list.html
  misago/templates/misago/admin/attachments/list.html
  misago/templates/misago/admin/attachmenttypes/form.html
  misago/templates/misago/admin/bans/form.html
  misago/templates/misago/admin/bans/list.html
  misago/templates/misago/admin/categories/delete.html
  misago/templates/misago/admin/categories/form.html
  misago/templates/misago/admin/categories/list.html
  misago/templates/misago/admin/categoryroles/categoryroles.html
  misago/templates/misago/admin/categoryroles/form.html
  misago/templates/misago/admin/categoryroles/rolecategories.html
  misago/templates/misago/admin/conf/group.html
  misago/templates/misago/admin/conf/index.html
  misago/templates/misago/admin/datadownloads/form.html
  misago/templates/misago/admin/datadownloads/list.html
  misago/templates/misago/admin/errorpages/403.html
  misago/templates/misago/admin/generic/base.html
  misago/templates/misago/admin/generic/form.html
  misago/templates/misago/admin/generic/list.html
  misago/templates/misago/admin/generic/paginator.html
  misago/templates/misago/admin/index.html
  misago/templates/misago/admin/login.html
  misago/templates/misago/admin/messages.html
  misago/templates/misago/admin/navbar.html
  misago/templates/misago/admin/permissions_table.html
  misago/templates/misago/admin/ranks/form.html
  misago/templates/misago/admin/ranks/list.html
  misago/templates/misago/admin/roles/form.html
  misago/templates/misago/admin/roles/list.html
  misago/templates/misago/admin/users/ban.html
  misago/templates/misago/admin/users/delete.html
  misago/templates/misago/admin/users/edit.html
  misago/templates/misago/admin/users/list.html
  misago/templates/misago/admin/users/new.html
  misago/templates/misago/admin/warnings/form.html
  misago/templates/misago/admin/warnings/list.html
  misago/templates/misago/auth.html
  misago/templates/misago/base.html
  misago/templates/misago/categories/base.html
  misago/templates/misago/categories/list_item.html
  misago/templates/misago/errorpages/ban_message.html
  misago/templates/misago/footer.html
  misago/templates/misago/index.html
  misago/templates/misago/profile/ban_details.html
  misago/templates/misago/profile/base.html
  misago/templates/misago/profile/header.html
  misago/templates/misago/profile/username_history.html
  misago/templates/misago/thread/paginator.html
  misago/templates/misago/thread/posts/post/body-hidden.html
  misago/templates/misago/thread/thread.html
  misago/templates/misago/threadslist/private_threads.html
  misago/templates/misago/userslists/active_posters.html
  misago/templates/misago/userslists/rank.html
Labels: enhancement, theme

#1158 Remove constants modules, move constants to app-level init modules
  misago/categories/__init__.py
  misago/categories/constants.py
  misago/categories/models.py
  misago/conftest.py
  misago/users/__init__.py
  misago/users/bans.py
  misago/users/constants.py
  misago/users/management/commands/invalidatebans.py
  misago/users/migrations/0017_move_bans_to_cache_version.py
  misago/users/models/ban.py
  misago/users/tests/test_bans.py
Labels: backend, enhancement

#1162 Remove misago.core.cache module
  misago/admin/views/index.py
  misago/categories/models.py
  misago/core/cache.py
  misago/legal/models.py
  misago/legal/utils.py
Labels: backend, enhancement

#1163 Remove misago.core.setup
  misago/core/setup.py
  misago/core/tests/test_setup.py
Labels: backend, enhancement

#1164 Make misago.conf pass pylint
  devproject/settings.py
  misago/conf/defaults.py
  misago/conf/forms.py
  misago/conf/models.py
  misago/conf/test.py
  misago/conf/tests/test_context_processors.py
  misago/conf/tests/test_getting_dynamic_settings_values.py
  misago/conf/tests/test_overridding_dynamic_settings.py
  misago/conf/utils.py
  misago/conf/views.py
Labels: backend, enhancement

#1166 Add format to pylint disables
  .pylintrc
Labels: backend, enhancement, tooling

#1169 Move misago admin to pytests
  devproject/urls.py
  misago/admin/auth.py
  misago/admin/middleware.py
  misago/admin/tests/test_404_view.py
  misago/admin/tests/test_admin_hierarchy.py
  misago/admin/tests/test_admin_index.py
  misago/admin/tests/test_admin_index_view.py
  misago/admin/tests/test_admin_site_hierarchy.py
  misago/admin/tests/test_admin_views.py
  misago/admin/tests/test_admin_views_are_protected.py
  misago/admin/tests/test_authorization.py
  misago/admin/tests/test_forms.py
  misago/admin/tests/test_generic_admin_list_view.py
  misago/admin/tests/test_login_to_admin.py
  misago/admin/tests/test_logout_from_admin.py
  misago/admin/tests/test_protected_urls_detection.py
  misago/admin/tests/test_yesno_switch.py
  misago/admin/views/__init__.py
  misago/admin/views/auth.py
  misago/admin/views/errorpages.py
  misago/admin/views/generic/list.py
  misago/conftest.py
  misago/test.py
  misago/users/views/admin/users.py
Labels: backend, enhancement

#1168 Update social auth to 2.0 and django-mptt to 0.9.1
  requirements.in
  requirements.txt
Labels: backend, enhancement

#1175 Dev tweaks
  dev
  devproject/settings.py
Labels: enhancement, tooling
