Repository rafalp/Misago, pull requests merged in 2018-08, with the labels that each got.

#1019 User data download
  frontend/src/components/options/delete-account.js
  frontend/src/components/options/download-data.js
  frontend/src/components/options/root.js
  misago/conf/context_processors.py
  misago/conf/defaults.py
  misago/project_template/cron.txt
  misago/project_template/project_name/settings.py
  misago/project_template/userdata/README.txt
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/templates/misago/admin/datadownloads/form.html
  misago/templates/misago/admin/datadownloads/list.html
  misago/templates/misago/emails/data_download.html
  misago/templates/misago/emails/data_download.txt
  misago/threads/signals.py
  misago/users/admin.py
  misago/users/api/users.py
  misago/users/apps.py
  misago/users/datadownloads/__init__.py
  misago/users/datadownloads/dataarchive.py
  misago/users/forms/admin.py
  misago/users/management/commands/expireuserdatadownloads.py
  misago/users/management/commands/prepareuserdatadownloads.py
  misago/users/migrations/0014_datadownload.py
  misago/users/models/__init__.py
  misago/users/models/datadownload.py
  misago/users/serializers/__init__.py
  misago/users/serializers/auth.py
  misago/users/serializers/datadownload.py
  misago/users/signals.py
  misago/users/tests/test_audittrail.py
  misago/users/tests/test_datadownloads.py
  misago/users/tests/test_datadownloads_dataarchive.py
  misago/users/tests/test_datadownloadsadmin_views.py
  misago/users/tests/test_expireuserdatadownloads.py
  misago/users/tests/test_prepareuserdatadownloads.py
  misago/users/tests/test_user_datadownloads_api.py
  misago/users/tests/test_user_requestdatadownload_api.py
  misago/users/tests/test_useradmin_views.py
  misago/users/urls/__init__.py
  misago/users/views/admin/datadownloads.py
  misago/users/views/admin/users.py
  requirements.txt
Labels: python, react.js

#1043 fix avatar gallery when using cloud storage
  misago/users/avatars/gallery.py
  misago/users/models/avatargallery.py
Labels: bug, python

#1044 Rename anonymize_content to anonymize_data
  misago/categories/signals.py
  misago/threads/signals.py
  misago/threads/tests/test_anonymize_data.py
  misago/threads/tests/test_delete_user_likes.py
  misago/users/models/user.py
  misago/users/signals.py
  misago/users/tests/test_user_model.py
Labels: python

#1045 Add deleteinactiveusers management command
  misago/conf/defaults.py
  misago/project_template/cron.txt
  misago/project_template/project_name/settings.py
  misago/users/management/commands/deleteinactiveusers.py
  misago/users/tests/test_deleteinactiveusers.py
Labels: python

#1047 Legal agreements versions
  frontend/src/components/RegisterLegalFootnote.js
  frontend/src/components/accept-agreement.js
  frontend/src/components/register.js
  frontend/src/components/social-auth/complete.js
  frontend/src/components/social-auth/register.js
  frontend/src/initializers/components/accept-agreement.js
  frontend/src/utils/validators.js
  frontend/style/flavor/modals.less
  frontend/style/index.less
  frontend/style/misago/agreement-overlay.less
  misago/legal/admin.py
  misago/legal/api.py
  misago/legal/apps.py
  misago/legal/context_processors.py
  misago/legal/forms.py
  misago/legal/migrations/0002_agreement_useragreement.py
  misago/legal/migrations/0003_create_agreements_from_settings.py
  misago/legal/models.py
  misago/legal/signals.py
  misago/legal/tests.py
  misago/legal/tests/__init__.py
  misago/legal/tests/test_admin_views.py
  misago/legal/tests/test_api.py
  misago/legal/tests/test_context_processors.py
  misago/legal/tests/test_required_agreement.py
  misago/legal/tests/test_utils.py
  misago/legal/tests/test_views.py
  misago/legal/urls/__init__.py
  misago/legal/urls/api.py
  misago/legal/utils.py
  misago/legal/views.py
  misago/legal/views/__init__.py
  misago/legal/views/admin.py
  misago/legal/views/legal.py
  misago/static/misago/css/misago.css
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/templates/misago/admin/agreements/form.html
  misago/templates/misago/admin/agreements/list.html
  misago/templates/misago/admin/users/edit.html
  misago/templates/misago/base.html
  misago/templates/misago/privacy_policy.html
  misago/templates/misago/required_agreement.html
  misago/templates/misago/terms_of_service.html
  misago/urls.py
  misago/users/api/userendpoints/create.py
  misago/users/forms/register.py
  misago/users/migrations/0015_user_agreements.py
  misago/users/models/datadownload.py
  misago/users/models/user.py
  misago/users/registration.py
  misago/users/social/pipeline.py
  misago/users/tests/test_social_pipeline.py
  misago/users/tests/test_user_create_api.py
  misago/users/tests/test_useradmin_views.py
Labels: backend, client, feature

#1052 Rename audit trail created_at to created_on
  misago/users/migrations/0012_audittrail.py
  misago/users/models/audittrail.py
  misago/users/signals.py
  misago/users/tests/test_audittrail.py
Labels: backend, enchancement

#1056 Fix legal links missing in footer
  misago/templates/misago/footer.html
Labels: bug, client

#1074 Handle multiple users returned by get_by_username_or_email
  misago/users/models/user.py
  misago/users/tests/test_user_model.py
Labels: backend, bug, enchancement
