Repository rafalp/Misago, pull requests merged in 2019-07, with the labels that each got.

#1252 Fix CSS source not being decoded before displaying in editor
  misago/themes/admin/views.py
Labels: backend, bug

#1253 Dont cache cache versions
  misago/cache/test.py
  misago/cache/tests/test_getting_cache_versions.py
  misago/cache/tests/test_invalidating_caches.py
  misago/cache/versions.py
Labels: backend, bug

#1254 Remove default category flavors
  frontend/style/flavor/categories-flavors.less
  frontend/style/index.less
  misago/static/misago/css/misago.css
Labels: theme

#1255 Add metatags for sharing on twitter
  misago/templates/misago/base.html
  misago/templates/misago/profile/base.html
  misago/templates/misago/thread/thread.html
Labels: backend, enhancement, theme

#1256 Update translations
  misago/locale/en/LC_MESSAGES/django.mo
  misago/locale/en/LC_MESSAGES/django.po
  misago/locale/en/LC_MESSAGES/djangojs.mo
  misago/locale/en/LC_MESSAGES/djangojs.po
  misago/locale/es/LC_MESSAGES/django.mo
  misago/locale/es/LC_MESSAGES/django.po
  misago/locale/es/LC_MESSAGES/djangojs.mo
  misago/locale/es/LC_MESSAGES/djangojs.po
  misago/locale/fr/LC_MESSAGES/django.mo
  misago/locale/fr/LC_MESSAGES/django.po
  misago/locale/fr/LC_MESSAGES/djangojs.mo
  misago/locale/fr/LC_MESSAGES/djangojs.po
  misago/locale/ru/LC_MESSAGES/django.mo
  misago/locale/ru/LC_MESSAGES/django.po
  misago/locale/ru/LC_MESSAGES/djangojs.mo
  misago/locale/ru/LC_MESSAGES/djangojs.po
  misago/locale/tr/LC_MESSAGES/django.mo
  misago/locale/tr/LC_MESSAGES/django.po
  misago/locale/tr/LC_MESSAGES/djangojs.mo
  misago/locale/tr/LC_MESSAGES/djangojs.po
  misago/locale/zh_Hans/LC_MESSAGES/django.mo
  misago/locale/zh_Hans/LC_MESSAGES/django.po
  misago/locale/zh_Hans/LC_MESSAGES/djangojs.mo
  misago/locale/zh_Hans/LC_MESSAGES/djangojs.po
Labels: localization, meta

#1257 Update dependencies
  requirements.txt
Labels: backend

#1264 Update deps
  requirements.txt
Labels: enhancement

#1265 misago.markup app cleanup
  misago/conftest.py
  misago/markup/__init__.py
  misago/markup/api.py
  misago/markup/bbcode/code.py
  misago/markup/bbcode/hr.py
  misago/markup/bbcode/inline.py
  misago/markup/bbcode/quote.py
  misago/markup/finalize.py
  misago/markup/md/strikethrough.py
  misago/markup/parser.py
  misago/markup/tests/conftest.py
  misago/markup/tests/snapshots/__init__.py
  misago/markup/tests/snapshots/snap_test_code_bbcode.py
  misago/markup/tests/snapshots/snap_test_finalization.py
  misago/markup/tests/snapshots/snap_test_hr_bbcode.py
  misago/markup/tests/snapshots/snap_test_inline_bbcode.py
  misago/markup/tests/snapshots/snap_test_link_handling.py
  misago/markup/tests/snapshots/snap_test_parser.py
  misago/markup/tests/snapshots/snap_test_quote_bbcode.py
  misago/markup/tests/snapshots/snap_test_short_image_markdown.py
  misago/markup/tests/snapshots/snap_test_strikethrough_markdown.py
  misago/markup/tests/test_api.py
  misago/markup/tests/test_checksums.py
  misago/markup/tests/test_code_bbcode.py
  misago/markup/tests/test_finalise.py
  misago/markup/tests/test_finalization.py
  misago/markup/tests/test_hr_bbcode.py
  misago/markup/tests/test_inline_bbcode.py
  misago/markup/tests/test_link_handling.py
  misago/markup/tests/test_mentions.py
  misago/markup/tests/test_parser.py
  misago/markup/tests/test_parsing_api.py
  misago/markup/tests/test_quote_bbcode.py
  misago/markup/tests/test_short_image_markdown.py
  misago/markup/tests/test_strikethrough_markdown.py
  misago/test.py
  misago/threads/models/post.py
Labels: backend, enhancement

#1263 Add application HealthCheck
  misago/healthcheck/__init__.py
  misago/healthcheck/urls.py
  misago/healthcheck/views.py
  misago/urls.py
Labels: backend, feature

#1267 Add spoiler BBCode
  frontend/src/components/editor/actions/spoiler.js
  frontend/src/components/editor/index.js
  frontend/src/components/misago-markup.js
  frontend/style/flavor/markup.less
  frontend/style/misago/markup.less
  misago/markup/bbcode/spoiler.py
  misago/markup/finalize.py
  misago/markup/parser.py
  misago/markup/tests/snapshots/snap_test_finalization.py
  misago/markup/tests/snapshots/snap_test_spoiler_bbcode.py
  misago/markup/tests/test_finalization.py
  misago/markup/tests/test_spoiler_bbcode.py
  misago/static/misago/css/misago.css
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: backend, client, feature
