Repository rafalp/Misago, pull requests merged in 2019-01, with the labels that each got.

#1176 added redis to docker-compose.yml
  devproject/__init__.py
  devproject/celery.py
  devproject/settings.py
  docker-compose.yaml
  misago/threads/migrations/0001_initial.py
  misago/threads/migrations/0006_redo_partial_indexes.py
  misago/threads/migrations/0009_auto_20180326_0010.py
  misago/users/migrations/0001_initial.py
  misago/users/migrations/0005_dj_19_update.py
  misago/users/migrations/0009_redo_partial_indexes.py
  misago/users/migrations/0011_auto_20180331_2208.py
  misago/users/migrations/0014_datadownload.py
  requirements.in
  requirements.txt
Labels: backend, feature, tooling

#1188 Remove old cacheversion model
  misago/core/migrations/0003_delete_cacheversion.py
  misago/core/models.py
  misago/core/tests/test_chunk_queryset.py
Labels: backend, enhancement

#1190 Fix admin filters session store corruption
  misago/admin/tests/test_generic_admin_list_view.py
  misago/admin/views/generic/list.py
Labels: backend, bug

#1189 Add theme import/export
  misago/templates/misago/admin/agreements/form.html
  misago/templates/misago/admin/attachmenttypes/form.html
  misago/templates/misago/admin/bans/form.html
  misago/templates/misago/admin/categories/form.html
  misago/templates/misago/admin/categoryroles/form.html
  misago/templates/misago/admin/datadownloads/form.html
  misago/templates/misago/admin/generic/form.html
  misago/templates/misago/admin/ranks/form.html
  misago/templates/misago/admin/roles/form.html
  misago/templates/misago/admin/themes/assets/css-editor-form.html
  misago/templates/misago/admin/themes/assets/css-link-form.html
  misago/templates/misago/admin/themes/form.html
  misago/templates/misago/admin/themes/import.html
  misago/templates/misago/admin/themes/list.html
  misago/templates/misago/admin/users/ban.html
  misago/templates/misago/admin/users/edit.html
  misago/templates/misago/admin/users/new.html
  misago/templates/misago/admin/warnings/form.html
  misago/themes/admin/__init__.py
  misago/themes/admin/exporter.py
  misago/themes/admin/forms.py
  misago/themes/admin/importer.py
  misago/themes/admin/tests/conftest.py
  misago/themes/admin/tests/snapshots/snap_test_building_css_files.py
  misago/themes/admin/tests/test_building_css_files.py
  misago/themes/admin/tests/test_creating_and_deleting_css_files.py
  misago/themes/admin/tests/test_creating_and_deleting_css_links.py
  misago/themes/admin/tests/test_creating_and_editing_themes.py
  misago/themes/admin/tests/test_exporting_themes.py
  misago/themes/admin/tests/test_importing_themes.py
  misago/themes/admin/views.py
Labels: backend, feature

#1191 Don't read imported asset into memory
  misago/themes/admin/importer.py
Labels: backend, enhancement

#1196 Face-lift the theme to be easier to override/customize
  devproject/settings.py
  frontend/package-lock.json
  frontend/src/components/threads-list/list/diff-message.js
  frontend/src/components/user-menu/user-nav.js
  frontend/static/img/logo.png
  frontend/static/img/page-header.svg
  frontend/style/flavor/buttons.less
  frontend/style/flavor/dropdowns.less
  frontend/style/flavor/form.less
  frontend/style/flavor/list-group.less
  frontend/style/flavor/modals.less
  frontend/style/flavor/navbar.less
  frontend/style/flavor/navs.less
  frontend/style/flavor/page-footer.less
  frontend/style/flavor/page-header.less
  frontend/style/flavor/participants.less
  frontend/style/flavor/post.less
  frontend/style/flavor/posting.less
  frontend/style/flavor/scaffolding.less
  frontend/style/flavor/search-dropdown.less
  frontend/style/flavor/variables.less
  frontend/style/flavor/wells.less
  frontend/style/index.less
  frontend/style/misago/change-avatar.less
  frontend/style/misago/inputs.less
  frontend/style/misago/navbar.less
  frontend/style/misago/poll.less
  misago/faker/management/commands/createfakeusers.py
  misago/static/apple-touch-icon-114.png
  misago/static/apple-touch-icon-120.png
  misago/static/apple-touch-icon-144.png
  misago/static/apple-touch-icon-152.png
  misago/static/apple-touch-icon-167.png
  misago/static/apple-touch-icon-180.png
  misago/static/apple-touch-icon-57.png
  misago/static/apple-touch-icon-72.png
  misago/static/apple-touch-icon-76.png
  misago/static/apple-touch-icon-80.png
  misago/static/apple-touch-icon.png
  misago/static/blank-avatar.png
  misago/static/favicon.ico
  misago/static/misago/admin/img/misago.png
  misago/static/misago/admin/img/mred.png
  misago/static/misago/css/misago.css
  misago/static/misago/img/logo.png
  misago/static/misago/img/page-header.png
  misago/static/misago/img/page-header.svg
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/static/misago/js/vendor.js.map
  misago/static/og-image.jpg
  misago/templates/misago/admin/base.html
  misago/templates/misago/navbar.html
Labels: enhancement, theme

#1198 Cleanup fake data generators
  dev
  misago/conftest.py
  misago/faker/bans.py
  misago/faker/categories.py
  misago/faker/englishcorpus.py
  misago/faker/management/commands/createfakebans.py
  misago/faker/management/commands/createfakecategories.py
  misago/faker/management/commands/createfakefollowers.py
  misago/faker/management/commands/createfakehistory.py
  misago/faker/management/commands/createfakeposts.py
  misago/faker/management/commands/createfakethreads.py
  misago/faker/management/commands/createfakeusers.py
  misago/faker/posts.py
  misago/faker/tests/conftest.py
  misago/faker/tests/test_create_fake_bans_command.py
  misago/faker/tests/test_create_fake_categories_command.py
  misago/faker/tests/test_create_fake_followers_command.py
  misago/faker/tests/test_create_fake_history_command.py
  misago/faker/tests/test_create_fake_posts_command.py
  misago/faker/tests/test_create_fake_threads_command.py
  misago/faker/tests/test_create_fake_users_command.py
  misago/faker/tests/test_englishcorpus.py
  misago/faker/tests/test_fake_bans.py
  misago/faker/tests/test_fake_categories.py
  misago/faker/tests/test_fake_posts.py
  misago/faker/tests/test_fake_threads.py
  misago/faker/tests/test_fake_users.py
  misago/faker/threads.py
  misago/faker/users.py
  misago/faker/utils.py
  misago/users/models/user.py
Labels: enhancement, tooling
