Repository rafalp/Misago, pull requests merged in 2023-03, with the labels that each got.

#1462 Update embed youtube markup
  devproject/settings.py
  frontend/src/services/one-box.js
  misago/__init__.py
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client, backend

#1463 Fix #1460: fix default thread state to read for guests
  frontend/src/components/ThreadsList/ThreadsListItem.jsx
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1464 Add touch events to quote selection
  frontend/src/components/posting/PostingQuoteSelection.jsx
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1465 Remove Python 3.10 from tests matrix
  .github/workflows/tests.yml
Labels: meta

#1466 Use overlow-wrap instead of word-wrap
  frontend/src/services/one-box.js
  frontend/src/style/misago/dropdowns.less
  frontend/src/style/misago/markup.less
  frontend/src/style/misago/material-icons.less
  frontend/src/style/misago/page-header.less
  frontend/src/style/misago/post-feed.less
  frontend/src/style/misago/post.less
  frontend/src/style/misago/threads-lists.less
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
  misago/static/misago/js/misago.js.map
Labels: client

#1469 Check moderation perms for mod tools in footer
  frontend/src/components/thread/ThreadToolbarBottom.jsx
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1471 Set CSS class on body element depending on auth state
  misago/core/tests/test_body_css_class.py
  misago/templates/misago/base.html
Labels: backend, theme

#1472 Remove GET method for OAuth2 access token retrieval
  misago/conf/admin/forms/oauth2.py
  misago/conf/admin/tests/test_change_oauth2_settings.py
  misago/conf/migrations/0009_delete_oauth2_access_token_method.py
  misago/oauth2/client.py
  misago/oauth2/tests/test_get_access_token.py
  misago/oauth2/tests/test_oauth2_complete_view.py
  misago/templates/misago/admin/conf/oauth2_settings.html
Labels: backend

#1473 Add new `oauth2_validators` hook
  misago/hooks.py
  misago/oauth2/client.py
  misago/oauth2/tests/test_get_user_data.py
  misago/oauth2/tests/test_user_creation_from_data.py
  misago/oauth2/tests/test_user_data_validation.py
  misago/oauth2/tests/test_user_update_with_data.py
  misago/oauth2/user.py
  misago/oauth2/validation.py
  misago/oauth2/views.py
Labels: backend

#1476 Fix Social Auth headers
  frontend/src/components/social-auth/complete.js
  frontend/src/components/social-auth/header.js
  frontend/src/components/social-auth/register.js
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1482 Embed metadata for quote selection
  frontend/src/components/MarkupEditor/MarkupEditor.jsx
  frontend/src/components/posting/getQuoteMarkup.js
  misago/markup/bbcode/quote.py
  misago/markup/bbcode/spoiler.py
  misago/markup/mentions.py
  misago/markup/tests/snapshots/snap_test_escaping.py
  misago/markup/tests/snapshots/snap_test_parser.py
  misago/markup/tests/snapshots/snap_test_quote_bbcode.py
  misago/markup/tests/snapshots/snap_test_spoiler_bbcode.py
  misago/markup/tests/test_mentions.py
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client, backend

#1483 Fix mentions
  frontend/src/components/MarkupEditor/MarkupEditor.jsx
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1485 Quote styles update
  frontend/src/style/flavor/markup.less
  frontend/src/style/misago/markup.less
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
Labels: client

#1491 Update default icons
  misago/static/misago/apple-touch-icon.png
  misago/static/misago/favicon-16.png
  misago/static/misago/favicon-32.png
  misago/static/misago/favicon.ico
Labels: meta

#1496 Bump version to 0.31.0.dev1
  misago/__init__.py
Labels: meta

#1495 Make default icons high-contrast
  misago/static/misago/apple-touch-icon.png
  misago/static/misago/favicon-16.png
  misago/static/misago/favicon-32.png
  misago/static/misago/favicon.ico
Labels: client

#1494 Editor preview and focus tweaks
  frontend/src/components/MarkupEditor/MarkupEditor.jsx
  frontend/src/components/MarkupEditor/operations.js
  frontend/src/components/misago-markup.js
  frontend/src/style/misago/markup-editor.less
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1497 Add styles for nested quotes
  frontend/src/style/misago/markup.less
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
  misago/static/misago/js/hljs.js
  misago/static/misago/js/hljs.js.map
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/static/misago/js/vendor.js
  misago/static/misago/js/vendor.js.map
  misago/static/misago/js/zxcvbn.js
Labels: client

#1498 Compile client assets for production
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
  misago/static/misago/js/hljs.js
  misago/static/misago/js/hljs.js.map
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/static/misago/js/vendor.js
  misago/static/misago/js/vendor.js.map
  misago/static/misago/js/zxcvbn.js
Labels: client

#1499 Bump version to 0.31.0
  misago/__init__.py
Labels: meta

#1500 Sync translations with Transifex
  misago/locale/en/LC_MESSAGES/django.po
  misago/locale/en/LC_MESSAGES/djangojs.po
  misago/locale/hu/LC_MESSAGES/django.mo
  misago/locale/hu/LC_MESSAGES/django.po
  misago/locale/hu/LC_MESSAGES/djangojs.mo
  misago/locale/hu/LC_MESSAGES/djangojs.po
Labels: localization, meta

#1502 Add missing images, bump ver to 0.31.1
  misago/__init__.py
  misago/static/misago/img/attachment-403.png
  misago/static/misago/img/attachment-404.png
  misago/static/misago/img/og-image.jpg
Labels: backend, critical

#1506 Change UI color to blue
  babel.config.js
  frontend/src/style/flavor/ranks-flavors.less
  frontend/src/style/flavor/variables.less
  misago/admin/src/style/controls.scss
  misago/admin/src/style/index.scss
  misago/admin/src/style/navbar.scss
  misago/admin/src/style/side-nav.scss
  misago/admin/src/style/variables.scss
  misago/static/misago/admin/index.css
  misago/static/misago/admin/index.css.map
  misago/static/misago/admin/index.js
  misago/static/misago/admin/index.js.LICENSE.txt
  misago/static/misago/admin/index.js.map
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
  package-lock.json
  package.json
  webpack.config.js
Labels: client

#1508 Make theme name lead to its assets instead of info form
  misago/templates/misago/admin/themes/list.html
Labels: client

#1512 Don't show protected flag on posts to non-mods or authors
  frontend/src/style/flavor/post.less
  frontend/src/style/flavor/variables.less
  frontend/src/style/misago/post.less
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/static/misago/js/vendor.js
  misago/static/misago/js/vendor.js.map
  misago/templates/misago/thread/posts/post/flags.html
  misago/threads/permissions/threads.py
  misago/threads/serializers/post.py
Labels: backend

#1515 Add target=blank to attachments
  frontend/src/components/posts-list/post/attachments/attachment.js
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
  misago/templates/misago/thread/posts/post/attachments.html
Labels: client, backend

#1517 Set parent category poster in categories tree
  misago/categories/utils.py
Labels: backend

#1519 Ask for confirmation when user leaves unsaved reply
  frontend/src/components/posting/edit.js
  frontend/src/components/posting/reply.js
  frontend/src/components/posting/start-private.js
  frontend/src/components/posting/start.js
  frontend/src/services/posting.js
  misago/static/misago/js/misago.js
  misago/static/misago/js/misago.js.map
Labels: client

#1521 Fix spoiler reveal positioning
  frontend/src/style/flavor/markup.less
  frontend/src/style/misago/markup.less
  misago/static/misago/css/misago.css
  misago/static/misago/css/misago.css.map
Labels: client

#1522 Sync translations with Transifex
  misago/locale/en/LC_MESSAGES/django.po
  misago/locale/en/LC_MESSAGES/djangojs.po
  misago/locale/hu/LC_MESSAGES/djangojs.mo
  misago/locale/hu/LC_MESSAGES/djangojs.po
  misago/locale/pl/LC_MESSAGES/djangojs.mo
  misago/locale/pl/LC_MESSAGES/djangojs.po
  misago/locale/pt_BR/LC_MESSAGES/djangojs.mo
  misago/locale/pt_BR/LC_MESSAGES/djangojs.po
  misago/locale/zh_Hans/LC_MESSAGES/djangojs.mo
  misago/locale/zh_Hans/LC_MESSAGES/djangojs.po
Labels: localization

#1523 Version 0.32
  README.rst
  misago/__init__.py
Labels: meta

#1487 Fixed 1230 - used queryset iterator in chunk_queryset
  misago/core/pgutils.py
  misago/core/tests/test_chunk_queryset.py
Labels: backend
